name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: aws configure
      uses: aws-actions/configure-aws-credentials@v4
      with: 
        aws-access-key-id: ${{ secrets.AWS_USER_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_USER_SECRET_KEY }}  
        aws-region: ${{ secrets.AWS_REGION }} 

    - name: Login to Amanzone ECR
      uses: aws-action/amazon-ecr-login@v2
      

    - name: Build the Docker image
      run: docker build -t ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/bawa0017:v1 .

    - name: push image to dockerHUB
      run: docker push "${{ secrets.AWS_ACCOUNT_ID }}".dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/bawa0017:v1    

   
